In [97]:
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [84]:
paper=requests.get('https://cdn.digialm.com//per/g01/pub/585/touchstone/AssessmentQPHTMLMode1//GATE2564/GATE2564S3D9797/17706364899402389/CS26S32003741_GATE2564S3D9797E1.html#').text
soup= BeautifulSoup(paper,'lxml')

In [85]:
len(soup.find_all('td',class_='bold'))

442

In [86]:
for i in soup.find_all('td',class_='bold'):
    print(i.text)

Q.1

Options
MCQ
22848211141
Answered
A
Q.2

Options
MCQ
22848211143
Answered
C
Q.3

Options
MCQ
22848211138
Answered
A
Q.4

Options
MCQ
22848211145
Answered
A
Q.5

Options
MCQ
22848211139
Not Attempted and Marked For Review
 --
Q.6

Options
MCQ
22848211140
Answered
A
Q.7

Options
MCQ
22848211146
Answered
D
Q.8

Options
MCQ
22848211144
Answered
B
Q.9

Options
MCQ
22848211137
Not Answered
 --
Q.10

Options
MCQ
22848211142
Not Attempted and Marked For Review
 --
Q.1

Options
MCQ
22848211151
Answered
B
Q.2

Options
MSQ
22848211164
Not Attempted and Marked For Review
 --
Q.3

Options
MSQ
22848211156
Not Attempted and Marked For Review
 --
Q.4

Options
MSQ
22848211157
Answered
B,D
Q.5

Options
MCQ
22848211147
Answered
A
Q.6

4
NAT
22848211169
Answered
Q.7

Options
MCQ
22848211148
Not Answered
 --
Q.8

Options
MCQ
22848211149
Not Answered
 --
Q.9

Options
MCQ
22848211153
Marked For Review
D
Q.10

Options
MSQ
22848211161
Marked For Review
A,C,D
Q.11

Options
MSQ
22848211167
Not Attempted and Marked For Review
 --
Q.12

3
NAT
22848211168
Marked For Review
Q.13

Options
MSQ
22848211155
Not Attempted and Marked For Review
 --
Q.14

Options
MSQ
22848211158
Answered
A,B,D
Q.15

Options
MCQ
22848211154
Answered
A
Q.16

Options
MSQ
22848211166
Not Attempted and Marked For Review
 --
Q.17

Options
MCQ
22848211152
Not Answered
 --
Q.18

2
NAT
22848211171
Answered
Q.19

Options
MCQ
22848211150
Answered
A
Q.20

Options
MSQ
22848211162
Marked For Review
A
Q.21

10
NAT
22848211170
Answered
Q.22

Options
MSQ
22848211160
Marked For Review
B,C,D
Q.23

Options
MSQ
22848211163
Not Attempted and Marked For Review
 --
Q.24

Options
MSQ
22848211159
Not Attempted and Marked For Review
 --
Q.25

Options
MSQ
22848211165
Answered
A,C
Q.26

 --
NAT
22848211197
Not Attempted and Marked For Review
Q.27

Options
MCQ
22848211180
Answered
C
Q.28

Options
MSQ
22848211189
Not Answered
 --
Q.29

Options
MCQ
22848211172
Answered
C
Q.30

Options
MSQ
22848211191
Not Answered
 --
Q.31

Options
MCQ
22848211176
Not Answered
 --
Q.32

Options
MSQ
22848211184
Answered
B,C,D
Q.33

9.5
NAT
22848211200
Answered
Q.34

Options
MSQ
22848211182
Not Answered
 --
Q.35

Options
MSQ
22848211183
Not Answered
 --
Q.36

Options
MSQ
22848211192
Answered
B,C
Q.37

Options
MCQ
22848211177
Not Answered
 --
Q.38

Options
MSQ
22848211186
Not Answered
 --
Q.39

Options
MCQ
22848211179
Marked For Review
D
Q.40

 --
NAT
22848211195
Not Answered
Q.41

6
NAT
22848211198
Answered
Q.42

Options
MCQ
22848211175
Answered
C
Q.43

6
NAT
22848211201
Answered
Q.44

3
NAT
22848211193
Answered
Q.45

0.14
NAT
22848211194
Answered
Q.46

Options
MSQ
22848211187
Marked For Review
B,C
Q.47

Options
MSQ
22848211185
Not Answered
 --
Q.48

Options
MCQ
22848211173
Answered
C
Q.49

Options
MSQ
22848211188
Answered
B,D
Q.50

 --
NAT
22848211199
Not Answered
Q.51

15
NAT
22848211196
Answered
Q.52

Options
MSQ
22848211190
Answered
C,D
Q.53

Options
MCQ
22848211178
Not Answered
 --
Q.54

Options
MCQ
22848211174
Answered
B
Q.55

Options
MCQ
22848211181
Not Answered
 --

In [87]:
soup.find_all('td',class_='bold')[18].text

'22848211138'

In [88]:
id=[]
x=soup.find_all('td',class_='bold')
for i in range(4,len(x)):
    if x[i].text.isnumeric():
        if int(x[i].text) > 2000000 :
            id.append(soup.find_all('td',class_='bold')[i].text)
temp={'qu_id':id}
table= pd.DataFrame(temp)
table

          qu_id
0   22848211141
1   22848211143
2   22848211138
3   22848211145
4   22848211139
..          ...
60  22848211196
61  22848211190
62  22848211178
63  22848211174
64  22848211181

[65 rows x 1 columns]

In [92]:
!pip install openpyxl

Requirement already satisfied: openpyxl in e:\code\anaconda\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in e:\code\anaconda\lib\site-packages (from openpyxl) (2.0.0)

In [95]:
table.to_excel('idd.xlsx',index=False)

In [99]:
pd.read_csv("finalX_cs.csv")

   Q_Type             Key  Marks  Q_No         Q_id
0     MCQ               B      1     1  22848211139
1     MCQ               C      1     2  22848211146
2     MCQ               C      1     3  22848211143
3     MCQ               D      1     4  22848211137
4     MCQ               C      1     5  22848211138
..    ...             ...    ...   ...          ...
60    NAT  65536 to 65536      2    61  22848211199
61    NAT          7 to 7      2    62  22848211193
62    NAT          4 to 4      2    63  22848211184
63    NAT      9.5 to 9.5      2    64  22848211189
64    NAT          6 to 6      2    65  22848211183

[65 rows x 5 columns]